name: market_mate
description: "Food distribution and sale made easy with MARKETMATE."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.3.1
  shared_preferences: ^2.5.4
  smooth_page_indicator: ^2.0.1
  file_picker: ^10.3.10
  image_picker: ^1.2.1
  flutter_svg: ^2.2.4
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  cached_network_image: ^3.4.1
  provider: ^6.1.5+1
  http: ^1.6.0
  jwt_decoder: ^2.0.1
  lottie: ^3.3.3
  socket_io_client: ^3.1.0
  firebase_messaging: ^15.2.4
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  fonts:
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/fonts/static/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/static/PlusJakartaSans-Italic.ttf
          style: italic
        - asset: assets/fonts/static/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/static/PlusJakartaSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/static/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/static/PlusJakartaSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/static/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/static/PlusJakartaSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/static/PlusJakartaSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/static/PlusJakartaSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/mm_icon_padded.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/mm_icon_padded.png"
  remove_alpha_ios: true
  min_sdk_android: 21